# Generated by Django 3.2.8 on 2021-11-19 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_created',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
