# Generated by Django 3.2.8 on 2021-11-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_book_created_book_date_checked_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date_returned',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
