# Generated by Django 3.2.8 on 2021-11-19 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211119_1554'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
