# Generated by Django 3.2.8 on 2021-11-19 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_delete_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='price',
        ),
    ]
