# Generated by Django 3.2.8 on 2021-11-19 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_book_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='date_checked_out',
        ),
    ]
